org.gradle.jvmargs=-Xmx3G

mod_id=twilight_forest_final_boss
mod_version=2.1.2
mod_group_id=net.psunset

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.248
neoforge_version_range=[21,)
twilightforest_version=4.8.3345
twilightforest_version_range=[4.8,)
geckolib_version=4.9.2
geckolib_version_range=[4,)
