modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Twilight Forest Final Boss"
authors = "D_Angry_Modder, LShiftLess"
description = '''An additional mod to add the final boss to Twilight Forest.'''
logoFile = "icon.png"

[[mixins]]
config = "twilightforestfinalboss.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "geckolib"
type = "required"
versionRange = "${geckolib_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "twilightforest"
type = "required"
versionRange = "${twilightforest_version_range}"
ordering = "NONE"
side = "BOTH"






